### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by powerdollkirby** [crolbar/matm#5]
trying to search for anime
```
thread 'main' panicked at src/ani/ani_select.rs:25:70:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace    
```

trying to play a movie
```
avatar
Couldn't deserialize sources page. Maybe the provier server is down?      
```

manga works fine.

both git and bin versions

**Comment by crolbar** [comment]
made an release [v2.2](https://github.com/crolbar/matm/releases/tag/v2.2) that should fix the issue that you are having with the anime scraper

about the movie scraper - rabbitstream (the provider that flixhq.to uses) changed their encryption method and i don't have time at the moment to find a solution

**Comment by powerdoll** [comment]
> made an release [v2.2](https://github.com/crolbar/matm/releases/tag/v2.2) that should fix the issue that you are having with the anime scraper
> 
yeah it's working now, ty

> about the movie scraper - rabbitstream (the provider that flixhq.to uses) changed their encryption method and i don't have time at the moment to find a solution

no worries, take your time

**Comment by powerdollkirby** [comment]
> made an release [v2.2](https://github.com/crolbar/matm/releases/tag/v2.2) that should fix the issue that you are having with the anime scraper
> 
yeah it's working now, ty

> about the movie scraper - rabbitstream (the provider that flixhq.to uses) changed their encryption method and i don't have time at the moment to find a solution

no worries, take your time

**Comment by dillfrescott** [comment]
yeah was about to say the movies and show option is a bit broken. Glad to see its being worked on!

**Comment by powerdollkirby** [comment]
yayyyy it's working >:D
