### ISSUE TITLE
"No Internet" Error.

### ISSUE THREAD

**Issue by WinnerWind** [crolbar/matm#6]
Arch Linux x86_64

when using any function of matm, installed via `matm-bin` (AUR, `matm-git` is infeasable as my PC is too slow to compile anything), I get the error "No Internet Connection" even though I am connected.
![image](https://github.com/crolbar/matm/assets/71366717/ea954fea-6db0-486c-a006-3d1548fa35c1)
How do I fix this?

**Comment by crolbar** [comment]
Sorry for the poor error message.
The error is occurring because you aren't getting the response from `aniwatchtv.to`. Maybe the domain is blocked by something? Is their website (`aniwatchtv.to`) working for you? It works on my end.

**Comment by WinnerWind** [comment]
Hi there!
You're right, `aniwatchtv.to` will not load in my browser. On further inspection it's actually banned by most major ISPs here. Sorry for your time!
As a suggestion, maybe a more descript error message will come in handy. Something like `Unable to connect to host aniwatchtv.to. Is your internet working? Is the site blocked?`. That being said, sorry for taking your time!
